### ISSUE TITLE
Unable to capture from Celestron NexImage10

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo#413]
Short version: when I go to the imager tab and try preview an image from a NexImage 10 the capture fails.

`Linux dietpi 5.10.60-sunxi #21.08.2 SMP Tue Sep 14 16:28:44 UTC 2021 armv7l GNU/Linux`
`Armbian 20.11.6 Buster`
`Indigo 2.0-162`

![Screenshot_2021-10-27_12-13-23](https://user-images.githubusercontent.com/1131751/139132830-69523dac-1907-4e8d-8fc1-f6ad153aa518.png)
![Screenshot_2021-10-27_12-13-36](https://user-images.githubusercontent.com/1131751/139132832-ae82c9ab-e6a6-485f-b688-6a3596836934.png)

With log level set to DEBUG, there are a couple of suspicious messages:
```
free(): invalid pointer
munmap_chunk(): invalid pointer
```

Dmesg shows the camera attaching.
```
[ 1170.147915] usb 2-1: new high-speed USB device number 2 using ehci-platform
[ 1170.310115] usb 2-1: New USB device found, idVendor=199e, idProduct=8619, bcdDevice= 0.00
[ 1170.318377] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1170.325594] usb 2-1: Product: NexImage 10
[ 1170.329686] usb 2-1: Manufacturer: Celestron
[ 1170.334033] usb 2-1: SerialNumber: 29914056
[ 1170.397520] uvcvideo: Unknown video format 36314142-0000-0010-8000-00aa00389b71
[ 1170.404916] uvcvideo: Found UVC 1.10 device NexImage 10 (199e:8619)
[ 1170.414656] usbcore: registered new interface driver uvcvideo
[ 1170.420482] USB Video Class driver (1.1.1)
```

lsusb says `Bus 002 Device 002: ID 199e:8619 The Imaging Source Europe GmbH NexImage 10`

I've added the appropriate udev rules and loaded the UVC driver; indeed INDIGO sees the camera:
<details>
<summary>click to expand indigo log</summary>
```
12:00:46.465594 indigo_server: indigo_ccd_uvc[ccd_connect_callback:203]: uvc_open() -> Success
12:00:46.468908 indigo_server: DEVICE CONFIGURATION (199e:8619/29914056) ---
12:00:46.469344 indigo_server: Status: idle
12:00:46.469596 indigo_server: VideoControl:
12:00:46.469596 indigo_server: 	bcdUVC: 0x0110
12:00:46.470531 indigo_server: VideoStreaming(1):
12:00:46.470531 indigo_server: 	bEndpointAddress: 129
12:00:46.470531 indigo_server: 	Formats:
12:00:46.471928 indigo_server: 	FrameFormat(1)
12:00:46.471928 indigo_server: 		  bits per pixel: 8
12:00:46.473210 indigo_server: 		  GUID: 4752424700001000800000aa00389b71  (GRBG)
12:00:46.473480 indigo_server: 		  default frame: 1
12:00:46.473480 indigo_server: 		  aspect ratio: 1x1
12:00:46.473480 indigo_server: 		  interlace flags: 00
12:00:46.473480 indigo_server: 		  copy protect: 00
12:00:46.474141 indigo_server: 			FrameDescriptor(1)
12:00:46.474141 indigo_server: 			  capabilities: 00
12:00:46.474141 indigo_server: 			  size: 3872x2764
12:00:46.474141 indigo_server: 			  bit rate: 72000-72000
12:00:46.474141 indigo_server: 			  max frame size: 0
12:00:46.474141 indigo_server: 			  default interval: 1/3
12:00:46.474608 indigo_server: 			  interval[0]: 1/3
12:00:46.474789 indigo_server: 			  interval[1]: 1/2
12:00:46.474967 indigo_server: 			FrameDescriptor(2)
12:00:46.474967 indigo_server: 			  capabilities: 00
12:00:46.474967 indigo_server: 			  size: 3664x2748
12:00:46.474967 indigo_server: 			  bit rate: 72000-72000
12:00:46.474967 indigo_server: 			  max frame size: 0
12:00:46.474967 indigo_server: 			  default interval: 1/3
12:00:46.476032 indigo_server: 			  interval[0]: 1/3
12:00:46.476205 indigo_server: 			  interval[1]: 1/2
12:00:46.476374 indigo_server: 			FrameDescriptor(3)
12:00:46.476374 indigo_server: 			  capabilities: 00
12:00:46.476374 indigo_server: 			  size: 3840x2160
12:00:46.476374 indigo_server: 			  bit rate: 72000-72000
12:00:46.476374 indigo_server: 			  max frame size: 0
12:00:46.476374 indigo_server: 			  default interval: 1/4
12:00:46.476794 indigo_server: 			  interval[0]: 1/4
12:00:46.476945 indigo_server: 			  interval[1]: 1/3
12:00:46.477101 indigo_server: 			FrameDescriptor(4)
12:00:46.477101 indigo_server: 			  capabilities: 00
12:00:46.477101 indigo_server: 			  size: 2560x1440
12:00:46.477101 indigo_server: 			  bit rate: 72000-72000
12:00:46.477101 indigo_server: 			  max frame size: 0
12:00:46.477101 indigo_server: 			  default interval: 1/5
12:00:46.477522 indigo_server: 			  interval[0]: 1/5
12:00:46.477683 indigo_server: 			FrameDescriptor(5)
12:00:46.477683 indigo_server: 			  capabilities: 00
12:00:46.477683 indigo_server: 			  size: 1920x1080
12:00:46.477683 indigo_server: 			  bit rate: 72000-72000
12:00:46.477683 indigo_server: 			  max frame size: 0
12:00:46.477683 indigo_server: 			  default interval: 1/10
12:00:46.478184 indigo_server: 			  interval[0]: 1/10
12:00:46.478332 indigo_server: 			  interval[1]: 1/5
12:00:46.478629 indigo_server: 			FrameDescriptor(6)
12:00:46.478629 indigo_server: 			  capabilities: 00
12:00:46.478629 indigo_server: 			  size: 1280x960
12:00:46.478629 indigo_server: 			  bit rate: 72000-72000
12:00:46.478629 indigo_server: 			  max frame size: 0
12:00:46.478629 indigo_server: 			  default interval: 1/25
12:00:46.479000 indigo_server: 			  interval[0]: 1/25
12:00:46.479130 indigo_server: 			  interval[1]: 1/20
12:00:46.479261 indigo_server: 			  interval[2]: 1/15
12:00:46.479384 indigo_server: 			  interval[3]: 1/10
12:00:46.479501 indigo_server: 			  interval[4]: 1/5
12:00:46.479637 indigo_server: 			FrameDescriptor(7)
12:00:46.479637 indigo_server: 			  capabilities: 00
12:00:46.479637 indigo_server: 			  size: 1280x720
12:00:46.479637 indigo_server: 			  bit rate: 72000-72000
12:00:46.479637 indigo_server: 			  max frame size: 0
12:00:46.479637 indigo_server: 			  default interval: 1/30
12:00:46.479985 indigo_server: 			  interval[0]: 1/30
12:00:46.480118 indigo_server: 			  interval[1]: 1/25
12:00:46.480243 indigo_server: 			  interval[2]: 1/20
12:00:46.480376 indigo_server: 			  interval[3]: 1/15
12:00:46.480505 indigo_server: 			  interval[4]: 1/10
12:00:46.480649 indigo_server: 			FrameDescriptor(8)
12:00:46.480649 indigo_server: 			  capabilities: 00
12:00:46.480649 indigo_server: 			  size: 640x480
12:00:46.480649 indigo_server: 			  bit rate: 72000-72000
12:00:46.480649 indigo_server: 			  max frame size: 0
12:00:46.480649 indigo_server: 			  default interval: 1/90
12:00:46.480989 indigo_server: 			  interval[0]: 1/90
12:00:46.481118 indigo_server: 			  interval[1]: 1/80
12:00:46.481238 indigo_server: 			  interval[2]: 1/70
12:00:46.481354 indigo_server: 			  interval[3]: 1/60
12:00:46.481480 indigo_server: 			  interval[4]: 1/50
12:00:46.481600 indigo_server: 			  interval[5]: 1/40
12:00:46.481727 indigo_server: 			  interval[6]: 1/30
12:00:46.481967 indigo_server: 			  interval[7]: 1/25
12:00:46.482124 indigo_server: 			  interval[8]: 1/20
12:00:46.482254 indigo_server: 			  interval[9]: 1/15
12:00:46.482399 indigo_server: 			  interval[10]: 1/10
12:00:46.482535 indigo_server: 	FrameFormat(2)
12:00:46.482535 indigo_server: 		  bits per pixel: 8
12:00:46.482724 indigo_server: 		  GUID: 5938303000001000800000aa00389b71  (Y800)
12:00:46.482855 indigo_server: 		  default frame: 1
12:00:46.482855 indigo_server: 		  aspect ratio: 1x1
12:00:46.482855 indigo_server: 		  interlace flags: 00
12:00:46.482855 indigo_server: 		  copy protect: 00
12:00:46.483151 indigo_server: 			FrameDescriptor(1)
12:00:46.483151 indigo_server: 			  capabilities: 00
12:00:46.483151 indigo_server: 			  size: 3872x2764
12:00:46.483151 indigo_server: 			  bit rate: 72000-72000
12:00:46.483151 indigo_server: 			  max frame size: 0
12:00:46.483151 indigo_server: 			  default interval: 1/3
12:00:46.483516 indigo_server: 			  interval[0]: 1/3
12:00:46.483651 indigo_server: 			  interval[1]: 1/2
12:00:46.483794 indigo_server: 			FrameDescriptor(2)
12:00:46.483794 indigo_server: 			  capabilities: 00
12:00:46.483794 indigo_server: 			  size: 3664x2748
12:00:46.483794 indigo_server: 			  bit rate: 72000-72000
12:00:46.483794 indigo_server: 			  max frame size: 0
12:00:46.483794 indigo_server: 			  default interval: 1/3
12:00:46.484144 indigo_server: 			  interval[0]: 1/3
12:00:46.484275 indigo_server: 			  interval[1]: 1/2
12:00:46.484420 indigo_server: 			FrameDescriptor(3)
12:00:46.484420 indigo_server: 			  capabilities: 00
12:00:46.484420 indigo_server: 			  size: 3840x2160
12:00:46.484420 indigo_server: 			  bit rate: 72000-72000
12:00:46.484420 indigo_server: 			  max frame size: 0
12:00:46.484420 indigo_server: 			  default interval: 1/4
12:00:46.484771 indigo_server: 			  interval[0]: 1/4
12:00:46.484906 indigo_server: 			  interval[1]: 1/3
12:00:46.485064 indigo_server: 			FrameDescriptor(4)
12:00:46.485064 indigo_server: 			  capabilities: 00
12:00:46.485064 indigo_server: 			  size: 2560x1440
12:00:46.485064 indigo_server: 			  bit rate: 72000-72000
12:00:46.485064 indigo_server: 			  max frame size: 0
12:00:46.485064 indigo_server: 			  default interval: 1/5
12:00:46.485601 indigo_server: 			  interval[0]: 1/5
12:00:46.485790 indigo_server: 			FrameDescriptor(5)
12:00:46.485790 indigo_server: 			  capabilities: 00
12:00:46.485790 indigo_server: 			  size: 1920x1080
12:00:46.485790 indigo_server: 			  bit rate: 72000-72000
12:00:46.485790 indigo_server: 			  max frame size: 0
12:00:46.485790 indigo_server: 			  default interval: 1/10
12:00:46.486802 indigo_server: 			  interval[0]: 1/10
12:00:46.486960 indigo_server: 			  interval[1]: 1/5
12:00:46.487099 indigo_server: 			FrameDescriptor(6)
12:00:46.487099 indigo_server: 			  capabilities: 00
12:00:46.487099 indigo_server: 			  size: 1280x960
12:00:46.487099 indigo_server: 			  bit rate: 72000-72000
12:00:46.487099 indigo_server: 			  max frame size: 0
12:00:46.487099 indigo_server: 			  default interval: 1/25
12:00:46.487385 indigo_server: 			  interval[0]: 1/25
12:00:46.487466 indigo_server: 			  interval[1]: 1/20
12:00:46.487538 indigo_server: 			  interval[2]: 1/15
12:00:46.487607 indigo_server: 			  interval[3]: 1/10
12:00:46.487668 indigo_server: 			  interval[4]: 1/5
12:00:46.487741 indigo_server: 			FrameDescriptor(7)
12:00:46.487741 indigo_server: 			  capabilities: 00
12:00:46.487741 indigo_server: 			  size: 1280x720
12:00:46.487741 indigo_server: 			  bit rate: 72000-72000
12:00:46.487741 indigo_server: 			  max frame size: 0
12:00:46.487741 indigo_server: 			  default interval: 1/30
12:00:46.487903 indigo_server: 			  interval[0]: 1/30
12:00:46.487955 indigo_server: 			  interval[1]: 1/25
12:00:46.488013 indigo_server: 			  interval[2]: 1/20
12:00:46.488067 indigo_server: 			  interval[3]: 1/15
12:00:46.488121 indigo_server: 			  interval[4]: 1/10
12:00:46.488174 indigo_server: 			FrameDescriptor(8)
12:00:46.488174 indigo_server: 			  capabilities: 00
12:00:46.488174 indigo_server: 			  size: 640x480
12:00:46.488174 indigo_server: 			  bit rate: 72000-72000
12:00:46.488174 indigo_server: 			  max frame size: 0
12:00:46.488174 indigo_server: 			  default interval: 1/90
12:00:46.488302 indigo_server: 			  interval[0]: 1/90
12:00:46.488345 indigo_server: 			  interval[1]: 1/80
12:00:46.488391 indigo_server: 			  interval[2]: 1/70
12:00:46.488436 indigo_server: 			  interval[3]: 1/60
12:00:46.488482 indigo_server: 			  interval[4]: 1/50
12:00:46.488530 indigo_server: 			  interval[5]: 1/40
12:00:46.488575 indigo_server: 			  interval[6]: 1/30
12:00:46.488619 indigo_server: 			  interval[7]: 1/25
12:00:46.488664 indigo_server: 			  interval[8]: 1/20
12:00:46.488707 indigo_server: 			  interval[9]: 1/15
12:00:46.488753 indigo_server: 			  interval[10]: 1/10
12:00:46.488801 indigo_server: 	FrameFormat(3)
12:00:46.488801 indigo_server: 		  bits per pixel: 16
12:00:46.488868 indigo_server: 		  GUID: 4241313600001000800000aa00389b71  (BA16)
12:00:46.488917 indigo_server: 		  default frame: 1
12:00:46.488917 indigo_server: 		  aspect ratio: 1x1
12:00:46.488917 indigo_server: 		  interlace flags: 00
12:00:46.488917 indigo_server: 		  copy protect: 00
12:00:46.489016 indigo_server: 			FrameDescriptor(1)
12:00:46.489016 indigo_server: 			  capabilities: 00
12:00:46.489016 indigo_server: 			  size: 3872x2764
12:00:46.489016 indigo_server: 			  bit rate: 72000-72000
12:00:46.489016 indigo_server: 			  max frame size: 0
12:00:46.489016 indigo_server: 			  default interval: 1/1
12:00:46.489138 indigo_server: 			  interval[0]: 1/1
12:00:46.489189 indigo_server: 			FrameDescriptor(2)
12:00:46.489189 indigo_server: 			  capabilities: 00
12:00:46.489189 indigo_server: 			  size: 3664x2748
12:00:46.489189 indigo_server: 			  bit rate: 72000-72000
12:00:46.489189 indigo_server: 			  max frame size: 0
12:00:46.489189 indigo_server: 			  default interval: 1/1
12:00:46.489313 indigo_server: 			  interval[0]: 1/1
12:00:46.489370 indigo_server: 			FrameDescriptor(3)
12:00:46.489370 indigo_server: 			  capabilities: 00
12:00:46.489370 indigo_server: 			  size: 3840x2160
12:00:46.489370 indigo_server: 			  bit rate: 72000-72000
12:00:46.489370 indigo_server: 			  max frame size: 0
12:00:46.489370 indigo_server: 			  default interval: 1/2
12:00:46.489604 indigo_server: 			  interval[0]: 1/2
12:00:46.489672 indigo_server: 			FrameDescriptor(4)
12:00:46.489672 indigo_server: 			  capabilities: 00
12:00:46.489672 indigo_server: 			  size: 2560x1440
12:00:46.489672 indigo_server: 			  bit rate: 72000-72000
12:00:46.489672 indigo_server: 			  max frame size: 0
12:00:46.489672 indigo_server: 			  default interval: 1/4
12:00:46.489803 indigo_server: 			  interval[0]: 1/4
12:00:46.489913 indigo_server: 			FrameDescriptor(5)
12:00:46.489913 indigo_server: 			  capabilities: 00
12:00:46.489913 indigo_server: 			  size: 1920x1080
12:00:46.489913 indigo_server: 			  bit rate: 72000-72000
12:00:46.489913 indigo_server: 			  max frame size: 0
12:00:46.489913 indigo_server: 			  default interval: 1/5
12:00:46.490056 indigo_server: 			  interval[0]: 1/5
12:00:46.490121 indigo_server: 			FrameDescriptor(6)
12:00:46.490121 indigo_server: 			  capabilities: 00
12:00:46.490121 indigo_server: 			  size: 1280x960
12:00:46.490121 indigo_server: 			  bit rate: 72000-72000
12:00:46.490121 indigo_server: 			  max frame size: 0
12:00:46.490121 indigo_server: 			  default interval: 1/15
12:00:46.490257 indigo_server: 			  interval[0]: 1/15
12:00:46.490310 indigo_server: 			  interval[1]: 1/10
12:00:46.490367 indigo_server: 			  interval[2]: 1/5
12:00:46.490424 indigo_server: 			FrameDescriptor(7)
12:00:46.490424 indigo_server: 			  capabilities: 00
12:00:46.490424 indigo_server: 			  size: 1280x720
12:00:46.490424 indigo_server: 			  bit rate: 72000-72000
12:00:46.490424 indigo_server: 			  max frame size: 0
12:00:46.490424 indigo_server: 			  default interval: 1/20
12:00:46.490553 indigo_server: 			  interval[0]: 1/20
12:00:46.490602 indigo_server: 			  interval[1]: 1/15
12:00:46.490653 indigo_server: 			  interval[2]: 1/10
12:00:46.490706 indigo_server: 			FrameDescriptor(8)
12:00:46.490706 indigo_server: 			  capabilities: 00
12:00:46.490706 indigo_server: 			  size: 640x480
12:00:46.490706 indigo_server: 			  bit rate: 72000-72000
12:00:46.490706 indigo_server: 			  max frame size: 0
12:00:46.490706 indigo_server: 			  default interval: 1/60
12:00:46.490839 indigo_server: 			  interval[0]: 1/60
12:00:46.490894 indigo_server: 			  interval[1]: 1/50
12:00:46.490942 indigo_server: 			  interval[2]: 1/40
12:00:46.490990 indigo_server: 			  interval[3]: 1/30
12:00:46.491037 indigo_server: 			  interval[4]: 1/25
12:00:46.491083 indigo_server: 			  interval[5]: 1/20
12:00:46.491130 indigo_server: 			  interval[6]: 1/15
12:00:46.491177 indigo_server: 			  interval[7]: 1/10
12:00:46.491223 indigo_server: 	FrameFormat(4)
12:00:46.491223 indigo_server: 		  bits per pixel: 16
12:00:46.491292 indigo_server: 		  GUID: 5931362000001000800000aa00389b71  (Y16 )
12:00:46.491342 indigo_server: 		  default frame: 1
12:00:46.491342 indigo_server: 		  aspect ratio: 1x1
12:00:46.491342 indigo_server: 		  interlace flags: 00
12:00:46.491342 indigo_server: 		  copy protect: 00
12:00:46.491438 indigo_server: 			FrameDescriptor(1)
12:00:46.491438 indigo_server: 			  capabilities: 00
12:00:46.491438 indigo_server: 			  size: 3872x2764
12:00:46.491438 indigo_server: 			  bit rate: 72000-72000
12:00:46.491438 indigo_server: 			  max frame size: 0
12:00:46.491438 indigo_server: 			  default interval: 1/1
12:00:46.491575 indigo_server: 			  interval[0]: 1/1
12:00:46.491633 indigo_server: 			FrameDescriptor(2)
12:00:46.491633 indigo_server: 			  capabilities: 00
12:00:46.491633 indigo_server: 			  size: 3664x2748
12:00:46.491633 indigo_server: 			  bit rate: 72000-72000
12:00:46.491633 indigo_server: 			  max frame size: 0
12:00:46.491633 indigo_server: 			  default interval: 1/1
12:00:46.491757 indigo_server: 			  interval[0]: 1/1
12:00:46.491808 indigo_server: 			FrameDescriptor(3)
12:00:46.491808 indigo_server: 			  capabilities: 00
12:00:46.491808 indigo_server: 			  size: 3840x2160
12:00:46.491808 indigo_server: 			  bit rate: 72000-72000
12:00:46.491808 indigo_server: 			  max frame size: 0
12:00:46.491808 indigo_server: 			  default interval: 1/2
12:00:46.492010 indigo_server: 			  interval[0]: 1/2
12:00:46.492077 indigo_server: 			FrameDescriptor(4)
12:00:46.492077 indigo_server: 			  capabilities: 00
12:00:46.492077 indigo_server: 			  size: 2560x1440
12:00:46.492077 indigo_server: 			  bit rate: 72000-72000
12:00:46.492077 indigo_server: 			  max frame size: 0
12:00:46.492077 indigo_server: 			  default interval: 1/4
12:00:46.492214 indigo_server: 			  interval[0]: 1/4
12:00:46.492265 indigo_server: 			FrameDescriptor(5)
12:00:46.492265 indigo_server: 			  capabilities: 00
12:00:46.492265 indigo_server: 			  size: 1920x1080
12:00:46.492265 indigo_server: 			  bit rate: 72000-72000
12:00:46.492265 indigo_server: 			  max frame size: 0
12:00:46.492265 indigo_server: 			  default interval: 1/5
12:00:46.492391 indigo_server: 			  interval[0]: 1/5
12:00:46.492441 indigo_server: 			FrameDescriptor(6)
12:00:46.492441 indigo_server: 			  capabilities: 00
12:00:46.492441 indigo_server: 			  size: 1280x960
12:00:46.492441 indigo_server: 			  bit rate: 72000-72000
12:00:46.492441 indigo_server: 			  max frame size: 0
12:00:46.492441 indigo_server: 			  default interval: 1/15
12:00:46.492562 indigo_server: 			  interval[0]: 1/15
12:00:46.492606 indigo_server: 			  interval[1]: 1/10
12:00:46.492652 indigo_server: 			  interval[2]: 1/5
12:00:46.492703 indigo_server: 			FrameDescriptor(7)
12:00:46.492703 indigo_server: 			  capabilities: 00
12:00:46.492703 indigo_server: 			  size: 1280x720
12:00:46.492703 indigo_server: 			  bit rate: 72000-72000
12:00:46.492703 indigo_server: 			  max frame size: 0
12:00:46.492703 indigo_server: 			  default interval: 1/20
12:00:46.492827 indigo_server: 			  interval[0]: 1/20
12:00:46.492870 indigo_server: 			  interval[1]: 1/15
12:00:46.492914 indigo_server: 			  interval[2]: 1/10
12:00:46.492961 indigo_server: 			FrameDescriptor(8)
12:00:46.492961 indigo_server: 			  capabilities: 00
12:00:46.492961 indigo_server: 			  size: 640x480
12:00:46.492961 indigo_server: 			  bit rate: 72000-72000
12:00:46.492961 indigo_server: 			  max frame size: 0
12:00:46.492961 indigo_server: 			  default interval: 1/60
12:00:46.493084 indigo_server: 			  interval[0]: 1/60
12:00:46.493128 indigo_server: 			  interval[1]: 1/50
12:00:46.493170 indigo_server: 			  interval[2]: 1/40
12:00:46.493215 indigo_server: 			  interval[3]: 1/30
12:00:46.493260 indigo_server: 			  interval[4]: 1/25
12:00:46.493305 indigo_server: 			  interval[5]: 1/20
12:00:46.493351 indigo_server: 			  interval[6]: 1/15
12:00:46.493396 indigo_server: 			  interval[7]: 1/10
12:00:46.493442 indigo_server: END DEVICE CONFIGURATION
12:00:46.494484 indigo_server: indigo_ccd_uvc[ccd_connect_callback:240]: uvc_get_stream_ctrl_format_size(..., 13, 3872, 2764, 0) -> Success
12:00:46.494745 indigo_server: indigo_ccd_uvc[ccd_connect_callback:245]: uvc_set_ae_mode(1) -> Pipe
12:00:46.495255 indigo_server: indigo_ccd_uvc[ccd_connect_callback:255]: uvc_get_exposure_abs(..., -> 1, UVC_GET_MIN) -> Success
12:00:46.495616 indigo_server: indigo_ccd_uvc[ccd_connect_callback:259]: uvc_get_exposure_abs(..., -> 300000, UVC_GET_MAX) -> Success
12:00:46.495863 indigo_server: indigo_ccd_uvc[ccd_connect_callback:264]: uvc_get_gain(..., -> 3, UVC_GET_INFO) -> Success
12:00:46.496110 indigo_server: indigo_ccd_uvc[ccd_connect_callback:269]: uvc_get_gain(..., -> 100, UVC_GET_CUR) -> Success
12:00:46.496358 indigo_server: indigo_ccd_uvc[ccd_connect_callback:273]: uvc_get_gain(..., -> 100, UVC_GET_MIN) -> Success
12:00:46.496609 indigo_server: indigo_ccd_uvc[ccd_connect_callback:277]: uvc_get_gain(..., -> 383, UVC_GET_MAX) -> Success
12:00:46.496859 indigo_server: indigo_ccd_uvc[ccd_connect_callback:282]: uvc_get_gamma(..., -> 383, UVC_GET_INFO) -> Pipe
12:00:46.505993 indigo_server: indigo_ccd_uvc[ccd_change_property:350]: uvc_get_stream_ctrl_format_size(..., 13, 3872, 2764, 0) -> Success
```
</details>

**Comment by ckuethe** [comment]
https://gist.github.com/05fb343454fa36cf39d480dafd0a72ad

Restarted indigo with `systemctl restart indigo`, increase log level to trace, connected/disconnected the celestron camera just to make sure something would show up, and then tried to take an image with the imager.

Let me know if there's anything else I can get for you.

**Comment by polakovic** [comment]
Thank you, I'll look at it.

**Comment by polakovic** [comment]
Pls. can you try with this change?

9364396d27fb2eab5be7c7b6134c1d5c85aab024

If it will not work, can you try also other "Capture modes"

Thank you...

**Comment by rumengb** [comment]
Hi Peter
Neximage 5 os not recognized by the driver at all:
this is ldusb

Bus 001 Device 004: ID 199e:8207 The Imaging Source Europe GmbH NexImage 5

**Comment by polakovic** [comment]
I didn’t change the detection code and it actually doesn’t use VID/PID. Did you enable the driver? Can you make a tracelog again?

**Comment by rumengb** [comment]
It was never detected but may work with this driver if detected.

**Comment by polakovic** [comment]
Oh sorry, you wrote NexImage 5, I missed it is not 10 :)

Maybe check this, it looks it needs firmware upgrade to become UVC compatible:

https://indilib.org/forum/ccds-dslrs/3320-experiences-with-celestron-neximage-cameras.html

**Comment by ckuethe** [comment]
OK, I got this while running `gdb indigo_server` while doing a single image preview (indigo 2.0-164)

```
(gdb) r --enable-debug --do-not-fork indigo_ccd_uvc
...
2:33:02.496137 indigo_server: indigo_ccd_uvc[ccd_connect_callback:241]: uvc_get_stream_ctrl_format_size(..., 13, 3872, 2764, 0) -> Success
12:33:02.496361 indigo_server: indigo_ccd_uvc[ccd_connect_callback:246]: uvc_set_ae_mode(1) -> Pipe
12:33:02.496593 indigo_server: indigo_ccd_uvc[ccd_connect_callback:256]: uvc_get_exposure_abs(..., -> 1, UVC_GET_MIN) -> Success
12:33:02.496752 indigo_server: indigo_ccd_uvc[ccd_connect_callback:260]: uvc_get_exposure_abs(..., -> 300000, UVC_GET_MAX) -> Success
12:33:02.496912 indigo_server: indigo_ccd_uvc[ccd_connect_callback:265]: uvc_get_gain(..., -> 3, UVC_GET_INFO) -> Success
12:33:02.497083 indigo_server: indigo_ccd_uvc[ccd_connect_callback:270]: uvc_get_gain(..., -> 100, UVC_GET_CUR) -> Success
12:33:02.497254 indigo_server: indigo_ccd_uvc[ccd_connect_callback:274]: uvc_get_gain(..., -> 100, UVC_GET_MIN) -> Success
12:33:02.497415 indigo_server: indigo_ccd_uvc[ccd_connect_callback:278]: uvc_get_gain(..., -> 383, UVC_GET_MAX) -> Success
12:33:02.497608 indigo_server: indigo_ccd_uvc[ccd_connect_callback:283]: uvc_get_gamma(..., -> 383, UVC_GET_INFO) -> Pipe
12:33:47.558132 indigo_server: indigo_ccd_uvc[ccd_change_property:371]: uvc_set_exposure_abs(10000) -> Success
12:33:47.559394 indigo_server: indigo_ccd_uvc[ccd_change_property:374]: uvc_set_gain(100) -> Success
12:33:47.559770 indigo_server: indigo_ccd_uvc[ccd_change_property:382]: uvc_stream_open_ctrl() -> Success
12:33:47.560445 indigo_server: indigo_ccd_uvc[ccd_change_property:386]: uvc_stream_start() -> Success
12:33:51.042459 indigo_server: indigo_ccd_uvc[exposure_callback:81]: uvc_stream_get_frame(...) -> Success

Thread 15 "indigo_server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcffff640 (LWP 851864)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:447
447	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:447
#1  0x00007ffff5327c92 in exposure_callback (device=0x555555bb7150) at indigo_ccd_uvc.c:85
#2  0x00007ffff6b5f6bc in timer_func (timer=0x7fffd42ba5c0) at indigo_timer.c:89
#3  0x00007ffff6b1a450 in start_thread (arg=0x7fffcffff640) at pthread_create.c:473
#4  0x00007ffff6a3cd53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by polakovic** [comment]
Pls. can you test with this change?

ad2c533753c7a0e6c9a951c8905c212e0f0b8fd9

Thank you...

**Comment by ckuethe** [comment]
That seems to have fixed my crash at least on x86_64 (haven't got around to compiling on armhf). 

Selecting capture mode, at least in the imager web UI fails unless I first select one in the control panel. Ain does detect all the capture modes without needing to run the control panel first.
![Screenshot_2021-11-15_14-23-59](https://user-images.githubusercontent.com/1131751/141864042-a77b3949-8627-4000-ae2c-88da5a608897.png)
![Screenshot_2021-11-15_14-23-39](https://user-images.githubusercontent.com/1131751/141863938-321a5a2c-145d-44b6-a415-6e1f4bd8789b.png)

![Screenshot_2021-11-15_14-24-46](https://user-images.githubusercontent.com/1131751/141864025-5fd59bd1-bf7d-4ea8-9a91-f304570dd18a.png)
![Screenshot_2021-11-15_14-25-01](https://user-images.githubusercontent.com/1131751/141864030-579bf0b4-d13b-45c0-bfd3-23b6757dd1a2.png)

So I selected a capture mode. The resulting image isn't debayered though.
![Screenshot_2021-11-15_14-27-25](https://user-images.githubusercontent.com/1131751/141864052-e2a3bc26-fcdf-4c54-80ee-27c2ac25a75a.png)
![Screenshot_2021-11-15_14-27-53](https://user-images.githubusercontent.com/1131751/141864054-8bad2f84-98d8-4f13-854d-82b5c28b9b0f.png)

**Comment by polakovic** [comment]
OK, thank you. But pls. can you make a trace log again? I have to find out what's wrong with the mode property.

**Comment by ckuethe** [comment]
Trace: https://gist.github.com/ckuethe/0ae44c974c02f41f74131723580e65cc

* Started indigo
* connected to webui
* selected imager
* took a preview exposure without selecting an image format (seems to defaulted to RAW8 3872x2764)
* ran ain-imager, connected to localhost
* took a preview exposure without explicitly choosing an image format (again it defaulted to RAW8 3872x2764)
* selected an image format ("3872x2764"), this change was reflected in the webui
* took a preview exposure

![nxi10_0](https://user-images.githubusercontent.com/1131751/142061662-3f65a5cd-ea73-4772-91d0-5c6ae9ad9643.png)
![nxi10_1](https://user-images.githubusercontent.com/1131751/142061684-4835e497-aded-4963-94b5-60e851a6d3ce.png)
![nxi10_2](https://user-images.githubusercontent.com/1131751/142061693-a18bd3eb-f3cb-401c-b4dc-a9cc82ed8cc9.png)

**Comment by polakovic** [comment]
There is a problem with the saved configuration for this device (with nonexistent camera mode selected). Pls. remove the configuration in the control panel (camera > main > configuration control > remove) and try again.

**Comment by ckuethe** [comment]
OK, removing that configuration allows the web imager to select a reasonable default format. Is that something that could be automatically detected and fixed?

**Comment by ckuethe** [comment]
I think this issue can be closed now, since I can capture from my neximage 10. There are other problems for which I will open new issues.
